/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FiyatlarRouteImport } from './routes/fiyatlar'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as IctihatRouteImport } from './routes/ictihat'
import { Route as KullanimSartlariRouteImport } from './routes/kullanim-sartlari'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SablonlarRouteImport } from './routes/sablonlar'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDurusmaRouteImport } from './routes/_authenticated/durusma'
import { Route as AuthenticatedHesapRouteImport } from './routes/_authenticated/hesap'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as KararlarKindRouteImport } from './routes/kararlar.$kind'
import { Route as PaylasTokenRouteImport } from './routes/paylas.$token'
import { Route as RehberDilekceNasilYazilirRouteImport } from './routes/rehber.dilekce-nasil-yazilir'
import { Route as RehberMaasBlokeItirazRouteImport } from './routes/rehber.maas-bloke-itiraz'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as ApiPublicVerifyRecaptchaRouteImport } from './routes/api/public/verify-recaptcha'
import { Route as ApiPublicDilekceFileRouteImport } from './routes/api/public/dilekce.$file'
import { Route as ApiPublicHooksDailyCaseAnalysisRouteImport } from './routes/api/public/hooks/daily-case-analysis'
import { Route as ApiPublicHooksRefreshUpdatesRouteImport } from './routes/api/public/hooks/refresh-updates'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FiyatlarRoute = FiyatlarRouteImport.update({
  id: '/fiyatlar',
  path: '/fiyatlar',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const IctihatRoute = IctihatRouteImport.update({
  id: '/ictihat',
  path: '/ictihat',
  getParentRoute: () => rootRouteImport,
} as any)
const KullanimSartlariRoute = KullanimSartlariRouteImport.update({
  id: '/kullanim-sartlari',
  path: '/kullanim-sartlari',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SablonlarRoute = SablonlarRouteImport.update({
  id: '/sablonlar',
  path: '/sablonlar',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDurusmaRoute = AuthenticatedDurusmaRouteImport.update({
  id: '/durusma',
  path: '/durusma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHesapRoute = AuthenticatedHesapRouteImport.update({
  id: '/hesap',
  path: '/hesap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const KararlarKindRoute = KararlarKindRouteImport.update({
  id: '/kararlar/$kind',
  path: '/kararlar/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const PaylasTokenRoute = PaylasTokenRouteImport.update({
  id: '/paylas/$token',
  path: '/paylas/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RehberDilekceNasilYazilirRoute =
  RehberDilekceNasilYazilirRouteImport.update({
    id: '/rehber/dilekce-nasil-yazilir',
    path: '/rehber/dilekce-nasil-yazilir',
    getParentRoute: () => rootRouteImport,
  } as any)
const RehberMaasBlokeItirazRoute = RehberMaasBlokeItirazRouteImport.update({
  id: '/rehber/maas-bloke-itiraz',
  path: '/rehber/maas-bloke-itiraz',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicVerifyRecaptchaRoute =
  ApiPublicVerifyRecaptchaRouteImport.update({
    id: '/api/public/verify-recaptcha',
    path: '/api/public/verify-recaptcha',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDilekceFileRoute = ApiPublicDilekceFileRouteImport.update({
  id: '/api/public/dilekce/$file',
  path: '/api/public/dilekce/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyCaseAnalysisRoute =
  ApiPublicHooksDailyCaseAnalysisRouteImport.update({
    id: '/api/public/hooks/daily-case-analysis',
    path: '/api/public/hooks/daily-case-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshUpdatesRoute =
  ApiPublicHooksRefreshUpdatesRouteImport.update({
    id: '/api/public/hooks/refresh-updates',
    path: '/api/public/hooks/refresh-updates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fiyatlar': typeof FiyatlarRoute
  '/gizlilik': typeof GizlilikRoute
  '/ictihat': typeof IctihatRoute
  '/kullanim-sartlari': typeof KullanimSartlariRoute
  '/kvkk': typeof KvkkRoute
  '/mcp': typeof McpRoute
  '/sablonlar': typeof SablonlarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/durusma': typeof AuthenticatedDurusmaRoute
  '/hesap': typeof AuthenticatedHesapRoute
  '/api/chat': typeof ApiChatRoute
  '/kararlar/$kind': typeof KararlarKindRoute
  '/paylas/$token': typeof PaylasTokenRoute
  '/rehber/dilekce-nasil-yazilir': typeof RehberDilekceNasilYazilirRoute
  '/rehber/maas-bloke-itiraz': typeof RehberMaasBlokeItirazRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/public/verify-recaptcha': typeof ApiPublicVerifyRecaptchaRoute
  '/api/public/dilekce/$file': typeof ApiPublicDilekceFileRoute
  '/api/public/hooks/daily-case-analysis': typeof ApiPublicHooksDailyCaseAnalysisRoute
  '/api/public/hooks/refresh-updates': typeof ApiPublicHooksRefreshUpdatesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fiyatlar': typeof FiyatlarRoute
  '/gizlilik': typeof GizlilikRoute
  '/ictihat': typeof IctihatRoute
  '/kullanim-sartlari': typeof KullanimSartlariRoute
  '/kvkk': typeof KvkkRoute
  '/mcp': typeof McpRoute
  '/sablonlar': typeof SablonlarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/durusma': typeof AuthenticatedDurusmaRoute
  '/hesap': typeof AuthenticatedHesapRoute
  '/api/chat': typeof ApiChatRoute
  '/kararlar/$kind': typeof KararlarKindRoute
  '/paylas/$token': typeof PaylasTokenRoute
  '/rehber/dilekce-nasil-yazilir': typeof RehberDilekceNasilYazilirRoute
  '/rehber/maas-bloke-itiraz': typeof RehberMaasBlokeItirazRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/public/verify-recaptcha': typeof ApiPublicVerifyRecaptchaRoute
  '/api/public/dilekce/$file': typeof ApiPublicDilekceFileRoute
  '/api/public/hooks/daily-case-analysis': typeof ApiPublicHooksDailyCaseAnalysisRoute
  '/api/public/hooks/refresh-updates': typeof ApiPublicHooksRefreshUpdatesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/fiyatlar': typeof FiyatlarRoute
  '/gizlilik': typeof GizlilikRoute
  '/ictihat': typeof IctihatRoute
  '/kullanim-sartlari': typeof KullanimSartlariRoute
  '/kvkk': typeof KvkkRoute
  '/mcp': typeof McpRoute
  '/sablonlar': typeof SablonlarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/durusma': typeof AuthenticatedDurusmaRoute
  '/_authenticated/hesap': typeof AuthenticatedHesapRoute
  '/api/chat': typeof ApiChatRoute
  '/kararlar/$kind': typeof KararlarKindRoute
  '/paylas/$token': typeof PaylasTokenRoute
  '/rehber/dilekce-nasil-yazilir': typeof RehberDilekceNasilYazilirRoute
  '/rehber/maas-bloke-itiraz': typeof RehberMaasBlokeItirazRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/public/verify-recaptcha': typeof ApiPublicVerifyRecaptchaRoute
  '/api/public/dilekce/$file': typeof ApiPublicDilekceFileRoute
  '/api/public/hooks/daily-case-analysis': typeof ApiPublicHooksDailyCaseAnalysisRoute
  '/api/public/hooks/refresh-updates': typeof ApiPublicHooksRefreshUpdatesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fiyatlar'
    | '/gizlilik'
    | '/ictihat'
    | '/kullanim-sartlari'
    | '/kvkk'
    | '/mcp'
    | '/sablonlar'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/durusma'
    | '/hesap'
    | '/api/chat'
    | '/kararlar/$kind'
    | '/paylas/$token'
    | '/rehber/dilekce-nasil-yazilir'
    | '/rehber/maas-bloke-itiraz'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/chat/$threadId'
    | '/api/public/verify-recaptcha'
    | '/api/public/dilekce/$file'
    | '/api/public/hooks/daily-case-analysis'
    | '/api/public/hooks/refresh-updates'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fiyatlar'
    | '/gizlilik'
    | '/ictihat'
    | '/kullanim-sartlari'
    | '/kvkk'
    | '/mcp'
    | '/sablonlar'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/durusma'
    | '/hesap'
    | '/api/chat'
    | '/kararlar/$kind'
    | '/paylas/$token'
    | '/rehber/dilekce-nasil-yazilir'
    | '/rehber/maas-bloke-itiraz'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/chat/$threadId'
    | '/api/public/verify-recaptcha'
    | '/api/public/dilekce/$file'
    | '/api/public/hooks/daily-case-analysis'
    | '/api/public/hooks/refresh-updates'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/fiyatlar'
    | '/gizlilik'
    | '/ictihat'
    | '/kullanim-sartlari'
    | '/kvkk'
    | '/mcp'
    | '/sablonlar'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/durusma'
    | '/_authenticated/hesap'
    | '/api/chat'
    | '/kararlar/$kind'
    | '/paylas/$token'
    | '/rehber/dilekce-nasil-yazilir'
    | '/rehber/maas-bloke-itiraz'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/chat/$threadId'
    | '/api/public/verify-recaptcha'
    | '/api/public/dilekce/$file'
    | '/api/public/hooks/daily-case-analysis'
    | '/api/public/hooks/refresh-updates'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FiyatlarRoute: typeof FiyatlarRoute
  GizlilikRoute: typeof GizlilikRoute
  IctihatRoute: typeof IctihatRoute
  KullanimSartlariRoute: typeof KullanimSartlariRoute
  KvkkRoute: typeof KvkkRoute
  McpRoute: typeof McpRoute
  SablonlarRoute: typeof SablonlarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  KararlarKindRoute: typeof KararlarKindRoute
  PaylasTokenRoute: typeof PaylasTokenRoute
  RehberDilekceNasilYazilirRoute: typeof RehberDilekceNasilYazilirRoute
  RehberMaasBlokeItirazRoute: typeof RehberMaasBlokeItirazRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicVerifyRecaptchaRoute: typeof ApiPublicVerifyRecaptchaRoute
  ApiPublicDilekceFileRoute: typeof ApiPublicDilekceFileRoute
  ApiPublicHooksDailyCaseAnalysisRoute: typeof ApiPublicHooksDailyCaseAnalysisRoute
  ApiPublicHooksRefreshUpdatesRoute: typeof ApiPublicHooksRefreshUpdatesRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiyatlar': {
      id: '/fiyatlar'
      path: '/fiyatlar'
      fullPath: '/fiyatlar'
      preLoaderRoute: typeof FiyatlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ictihat': {
      id: '/ictihat'
      path: '/ictihat'
      fullPath: '/ictihat'
      preLoaderRoute: typeof IctihatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kullanim-sartlari': {
      id: '/kullanim-sartlari'
      path: '/kullanim-sartlari'
      fullPath: '/kullanim-sartlari'
      preLoaderRoute: typeof KullanimSartlariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sablonlar': {
      id: '/sablonlar'
      path: '/sablonlar'
      fullPath: '/sablonlar'
      preLoaderRoute: typeof SablonlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/durusma': {
      id: '/_authenticated/durusma'
      path: '/durusma'
      fullPath: '/durusma'
      preLoaderRoute: typeof AuthenticatedDurusmaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hesap': {
      id: '/_authenticated/hesap'
      path: '/hesap'
      fullPath: '/hesap'
      preLoaderRoute: typeof AuthenticatedHesapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kararlar/$kind': {
      id: '/kararlar/$kind'
      path: '/kararlar/$kind'
      fullPath: '/kararlar/$kind'
      preLoaderRoute: typeof KararlarKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paylas/$token': {
      id: '/paylas/$token'
      path: '/paylas/$token'
      fullPath: '/paylas/$token'
      preLoaderRoute: typeof PaylasTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rehber/dilekce-nasil-yazilir': {
      id: '/rehber/dilekce-nasil-yazilir'
      path: '/rehber/dilekce-nasil-yazilir'
      fullPath: '/rehber/dilekce-nasil-yazilir'
      preLoaderRoute: typeof RehberDilekceNasilYazilirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rehber/maas-bloke-itiraz': {
      id: '/rehber/maas-bloke-itiraz'
      path: '/rehber/maas-bloke-itiraz'
      fullPath: '/rehber/maas-bloke-itiraz'
      preLoaderRoute: typeof RehberMaasBlokeItirazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/verify-recaptcha': {
      id: '/api/public/verify-recaptcha'
      path: '/api/public/verify-recaptcha'
      fullPath: '/api/public/verify-recaptcha'
      preLoaderRoute: typeof ApiPublicVerifyRecaptchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dilekce/$file': {
      id: '/api/public/dilekce/$file'
      path: '/api/public/dilekce/$file'
      fullPath: '/api/public/dilekce/$file'
      preLoaderRoute: typeof ApiPublicDilekceFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-case-analysis': {
      id: '/api/public/hooks/daily-case-analysis'
      path: '/api/public/hooks/daily-case-analysis'
      fullPath: '/api/public/hooks/daily-case-analysis'
      preLoaderRoute: typeof ApiPublicHooksDailyCaseAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-updates': {
      id: '/api/public/hooks/refresh-updates'
      path: '/api/public/hooks/refresh-updates'
      fullPath: '/api/public/hooks/refresh-updates'
      preLoaderRoute: typeof ApiPublicHooksRefreshUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDurusmaRoute: typeof AuthenticatedDurusmaRoute
  AuthenticatedHesapRoute: typeof AuthenticatedHesapRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDurusmaRoute: AuthenticatedDurusmaRoute,
  AuthenticatedHesapRoute: AuthenticatedHesapRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FiyatlarRoute: FiyatlarRoute,
  GizlilikRoute: GizlilikRoute,
  IctihatRoute: IctihatRoute,
  KullanimSartlariRoute: KullanimSartlariRoute,
  KvkkRoute: KvkkRoute,
  McpRoute: McpRoute,
  SablonlarRoute: SablonlarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  KararlarKindRoute: KararlarKindRoute,
  PaylasTokenRoute: PaylasTokenRoute,
  RehberDilekceNasilYazilirRoute: RehberDilekceNasilYazilirRoute,
  RehberMaasBlokeItirazRoute: RehberMaasBlokeItirazRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicVerifyRecaptchaRoute: ApiPublicVerifyRecaptchaRoute,
  ApiPublicDilekceFileRoute: ApiPublicDilekceFileRoute,
  ApiPublicHooksDailyCaseAnalysisRoute: ApiPublicHooksDailyCaseAnalysisRoute,
  ApiPublicHooksRefreshUpdatesRoute: ApiPublicHooksRefreshUpdatesRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
